name: Gerar Manifesto após uma Update

on:
  push:
    branches:
      - main-dev 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Hash-Calc
      run: |
        echo "{" > manifesto.json
        echo "  \"arquivos\": [" >> manifesto.json
        
        FIRST=true
        
        # O '< <(...)' evita o subshell e mantém a variável FIRST funcionando
        while read -r arquivo; do
          # calcular MD5
          HASH=$(md5sum "$arquivo" | awk '{print $1}')
          
          # interpreta o JSON
          if [ "$FIRST" = true ]; then
            FIRST=false
          else
            echo "," >> manifesto.json
          fi
          
          # path e hash inseridos no JSON
          echo "    { \"caminho\": \"$arquivo\", \"hash_esperado\": \"$HASH\" }" | tr -d '\n' >> manifesto.json
        done < <(find translated -type f)
        
        echo "" >> manifesto.json
        echo "  ]" >> manifesto.json
        echo "}" >> manifesto.json

    - name: Commit e Push do JSON
      run: |
        git config --global user.name "GitHub Action"
        git config --global user.email "action@github.com"
        
        # so dá commit se tiver mudado algo
        git add manifesto.json
        git diff --quiet && git diff --staged --quiet || (git commit -m "Auto: Atualizado manifesto.json com novos hashes" && git push)