name: Gerar Manifest após uma Update

on:
  push:
    branches:
      - main-dev 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Hash-Calc
      run: |
        echo "{" > manifest.json
        echo "  \"files\": [" >> manifest.json
        
        FIRST=true
        
        # O '< <(...)' evita o subshell e mantém a variável FIRST funcionando
        while read -r arquivo; do
          # calcular MD5
          HASH=$(md5sum "$arquivo" | awk '{print $1}')
          
          # interpreta o JSON
          if [ "$FIRST" = true ]; then
            FIRST=false
          else
            echo "," >> manifest.json
          fi
          
          # path e hash inseridos no JSON
          echo "    { \"path\": \"$arquivo\", \"hash\": \"$HASH\" }" | tr -d '\n' >> manifest.json
        done < <(find translated -type f)
        
        echo "" >> manifest.json
        echo "  ]" >> manifest.json
        echo "}" >> manifest.json

    - name: Commit e Push do JSON
      run: |
        git config --global user.name "GitHub Action"
        git config --global user.email "action@github.com"
        
        # so dá commit se tiver mudado algo
        git add manifest.json
        git diff --quiet && git diff --staged --quiet || (git commit -m "Atualizado 'manifest.json' com novas hashes após update." && git push)