name: Atualizar manifest

on:
  push:
    branches:
      - main-dev
  workflow_run:
    workflows:
      - Progresso da Tradução
    types:
      - completed

permissions:
  contents: write

concurrency:
  group: hash-generator
  cancel-in-progress: false

jobs:
  build:
    if: github.event_name == 'push' || (github.event_name == 'workflow_run' && github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.head_branch == 'dev')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event_name == 'workflow_run' && github.event.workflow_run.head_branch || github.ref_name }}

      - name: Hash-Calc
        run: |
          echo "{" > manifest.json
          echo "  \"files\": [" >> manifest.json

          FIRST=true

          while read -r arquivo; do
            HASH=$(md5sum "$arquivo" | awk '{print $1}')

            if [ "$FIRST" = true ]; then
              FIRST=false
            else
              echo "," >> manifest.json
            fi

            echo "    { \"path\": \"$arquivo\", \"hash\": \"$HASH\" }" | tr -d '\n' >> manifest.json
          done < <(find chapter*_windows -type f -path '*/traduzido/lang_pt.json' ! -path '*/traduzido/variantes/*' | sort)

          echo "" >> manifest.json
          echo "  ]" >> manifest.json
          echo "}" >> manifest.json

      - name: Commit e Push do JSON
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          DATA=$(date +%d/%m/%Y)

          git add manifest.json

          if ! git diff --cached --quiet; then
            git commit -m "Hashes atualizadas para ${DATA}."

            if [ "${{ github.event_name }}" = "workflow_run" ]; then
              BRANCH="${{ github.event.workflow_run.head_branch }}"
            else
              BRANCH="${GITHUB_REF_NAME}"
            fi

            git push origin HEAD:"$BRANCH"
          else
            echo "Nenhuma alteração para commitar."
          fi